### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by AbGedreht** [javierarce/tumblr-liked-photos-export#10]
I tried to download my 493 likes, but only got this error:

`C:\Ruby23-x64\bin>ruby export.rb`
`Downloading 500 posts`
`Unauthorized`
`Aaaaand we're done, parsed 20`

My username and OAuth Consumer Key is correct, is there any problem with the API?

**Comment by javierarce** [comment]
Hi, @AbGedreht. The API it's currently working for me. 

You can test if your API key is valid opening the following URL in your browser:

`http://api.tumblr.com/v2/blog/USERNAME.tumblr.com/likes?api_key=API_KEY`

Just replace USERNAME and API_KEY with your data.

**Comment by AbGedreht** [comment]
I opened the URL wihy my data and it seems to work, but still the script doesn't work for me :/

**Comment by iamlukesky** [comment]
@javierarce did you sort it out? I'm having the same problem.

**Comment by javierarce** [comment]
@iamlukesky: I'm afraid not, I couldn't reproduce the error. 

Does using the URL `http://api.tumblr.com/v2/blog/USERNAME.tumblr.com/likes?api_key=API_KEY` in the browser works for you?

**Comment by iamlukesky** [comment]
Yes that works just fine.

**Comment by iamlukesky** [comment]
Looking a bit closer at the code it's really strange that that would be the case. I don't really know ruby, how can I change the code to show the full error message, and not just the Unauthorized part?

**Comment by iamlukesky** [comment]
I found the probblem!

From readme.md:

> 5. Add two keys to your bash/zsh:  
> 
>         export TUMBLR_USERNAME="MY_FANTASTIC_TUMBLR_USERNAME"  
>         export TUMBLR_API_KEY="MY_DAUNTING_OAUTH_CONSUMER_KEY"  
>         
>         
>   Or simply update the `export.rb` file with your credentials:
>         
>         # Configuration
>         username = "MY_COOL_TUMBLR_USERNAME"
>         api_key  = "MY_OH_SO_NICE_OAUTH_CONSUMER_KEY"  

I had missed that I was supposed to remove `ENV[ ]` from the variable assignment.
