### ISSUE TITLE
nokogiri problem

### ISSUE THREAD

**Issue by nilsbyte** [javierarce/tumblr-liked-photos-export#16]
I am using the script on Windows 10 64 bit with Ruby 2.5.0

When running the script, I get the following error

```
1: from C:/Program Files/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Program Files/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
```

Installing nokogiri again does not solve the problem

```
C:\Tools\Web\tumblr-full-backup-master>gem install nokogiri -f
Nokogiri is built with the packaged libraries: libxml2-2.9.5, libxslt-1.1.30, zlib-1.2.11, libiconv-1.15.
Successfully installed nokogiri-1.8.1-x64-mingw32
Parsing documentation for nokogiri-1.8.1-x64-mingw32
Done installing documentation for nokogiri after 1 seconds
1 gem installed
```

**Comment by javierarce** [comment]
I don't think this is a problem with the code of my script, since it doesn't use nokogiri. And, if I'm not mistaken, that's also true for the  httparty gem (https://github.com/jnunemaker/httparty/blob/247d541f93e27d96e8226ec222a0c488886d1017/Gemfile)

**Comment by nilsbyte** [comment]
Well, it's a fresh install of Ruby and the httparty gem. I don't understand the problem here.

**Comment by javierarce** [comment]
Maybe if you use `gem dependency nokogiri --reverse-dependencies` you'll be able to find which gem is requiring `nokogiri`.

**Comment by nilsbyte** [comment]
```  Used by
    reverse_markdown-1.0.4 (nokogiri (>= 0)
```

**Comment by javierarce** [comment]
So I think this is not related with this script, sorry :/

**Comment by javierarce** [comment]
You are welcome, @nilsbyte.

**Comment by nilsbyte** [comment]
Thanks for pointing that out.
