### ISSUE TITLE
Undefined method error in get_photos

### ISSUE THREAD

**Issue by heisler98** [javierarce/tumblr-liked-photos-export#19]
Love the script. It was working great for the first 1,204 images (it reported a total of 5K in the beginning), until I was thrown this: 

> export.rb:55:in get_photos': undefined method [] for nil:NilClass (NoMethodError)
	from export.rb:133:in block in download
	from export.rb:127:in times
	from export.rb:127:in download
	from export.rb:145:in main

**Comment by javierarce** [comment]
Oh, sorry :/ I introduced some changes yesterday and I probably missed something. I'll have a look.

**Comment by javierarce** [comment]
Ok, I made some changes and was able to download +8k liked images. Can you try again?

**Comment by nd2s** [comment]
```
export.rb:114:in `download': undefined method `%' for nil:NilClass (NoMethodError)
```

With latest version.

**Comment by javierarce** [comment]
@nd2s can you manually check the API call? If you download the last version and run it again, it'll print a URL in the terminal. Open it in a browser and see if there's an error message.

**Comment by nd2s** [comment]
Yeah doesn't work -> Forbidden. Your program should catch that...

Problem was I did not allow viewing of likes in my settings.

**Comment by javierarce** [comment]
Thanks, I'll improve it with your feedback.

**Comment by javierarce** [comment]
Here's the change: https://github.com/javierarce/tumblr-liked-photos-export/commit/3449e11ee4687e26dddee2da123f93e24f2e5451

**Comment by heisler98** [comment]
It worked like a charm! Ran right past those exceptions. Thanks!
