### ISSUE TITLE
please help us

### ISSUE THREAD

**Issue by hyeonsuuu** [javierarce/tumblr-liked-photos-export#21]
I'm really new about those things. I actually tried to use this yesterday for 4 hours
but still having problems. :( below
export.rb:5:in `<main>': undefined local variable or method `[redacted API KEY]' for main:Object (NameError)
got this error. please save us I think so many people are looking for your git now because of their terrible decision but some of them cannot use this like me. I really hope you check this ASAP
thanks

**Comment by javierarce** [comment]
Hi, @hyeonsuuu … were you trying to paste your API_KEY in the `export.rb` file? You should have something like this

```
# Configuration
api_key      = "1233567890" 
username     = ARGV[0] || ENV["TUMBLR_USERNAME"]
image_dir    = ARGV.count == 2 ? ARGV[1] : (ARGV[1] || "images")
```

then you could run the file with `ruby export.rb username`

**Comment by javierarce** [comment]
I removed the API key you pasted in your first message because it could lead to some people getting access to your tumblr likes, etc.

**Comment by hyeonsuuu** [comment]
First I really appreciate your favor.
I still have a problem. :(
here's my procedure I did.
1. installed ruby, httparty.
2. got API key on tumblr.
3. pasted in the export.rb
4. so, should I change just username, API Key, limit I want to download..that's it?
..

 I saved like this below

require 'rubygems'
require 'httparty'

# Configuration
api_key      = "oEFHv8vyDwO7gX2Lws3ezY7IOY190H... my API key from tumblr"
username     = ARGV[0] || ENV "paste here my username"
image_dir    = ARGV.count == 2 ? ARGV[1] : (ARGV[1] || "images....should I change here?")
limit        = 3000  # number of posts requested each time

class TumblrPhotoExport

  attr_accessor :username, :api_key, :image_dir, :limit, :url

  def initialize(username, api_key, image_dir, limit)

    @username     = only put username
    @api_key      = only put api_key
    @image_dir    = image_dir
    @limit        = 3000
    @download_num = nil
    @before       = nil

    @url          = "http://api.tumblr.com/v2/blog/#{username}.tumblr.com/likes?api_key=#{API_key}"


    puts "\033[32mURL\033[0m"
    puts @url

**Comment by javierarce** [comment]
You can just add the API key in export.rb and indicate the username and folder using the command line like this:

`ruby export.rb username`
`ruby export.rb username directory`

In the first case the images will be downloaded to the default `images` directory.
In the second case they'll go to the directory you specify.

**Comment by hyeonsuuu** [comment]
so.. this is what I did..

<img width="606" alt="screen shot 2018-12-07 at 9 14 25 pm" src="https://user-images.githubusercontent.com/45656929/49647483-fee71c80-fa65-11e8-8da8-3e3e41815ea9.png">
<img width="566" alt="screen shot 2018-12-07 at 9 11 41 pm" src="https://user-images.githubusercontent.com/45656929/49647484-fee71c80-fa65-11e8-962a-3a2e9b1f9930.png">

**Comment by hyeonsuuu** [comment]
I installed all programs and changed all in export.rb so now it's working but still having a problem

If you get the "Unauthorized" error message, open the URL http://api.tumblr.com/v2/blog/USERNAME.tumblr.com/likes?api_key=API_KEY in your browser (replacing USERNAME and API_KEY with your own values). You should see a list of posts.

you mentioned this so I checked using my USERNAME and API_key.
what can I do for next step? I got almost 3000 likes on my tumblr so I cannot do save one by one

**Comment by javierarce** [comment]
What do you see when you open that URL in a browser?

**Comment by hyeonsuuu** [comment]
there are a lot. It starts with {"meta":{"status":200,"msg":"OK"}...
I think that shows my likes with words only

**Comment by javierarce** [comment]
No, that should show all the liked posts. How are you calling the script?

**Comment by hyeonsuuu** [comment]
you mean posts with images or vids? it seems like a post what I liked but looks like a script.

**Comment by hyeonsuuu** [comment]
I solved everything. Thank you for helping me I really appreciate. you're so nice.

**Comment by javierarce** [comment]
Nice to hear that. I'm glad it worked for you finally :)
