### ISSUE TITLE
Limit 9999 - Saves only 1109 images

### ISSUE THREAD

**Issue by nilsbyte** [javierarce/tumblr-liked-photos-export#7]
I am using the recent version of your script on OSX 10.11.4. I have over 2400 liked posts but your script only saves 1109 images. The strange thing is that the terminal output looks like it's continuing with download, but the images folder stays at 1109 images.

**Comment by nilsbyte** [comment]
When i decrease the limit from 10 to 1, it repeats a certain liked image (which is available, not deleted on tumblr) in an infinite loop.

**Comment by javierarce** [comment]
Have you tried to change the offset? Could you try to set `offset` to 1100 [here](https://github.com/javierarce/tumblr-photo-export/blob/master/export.rb#L8)?

**Comment by javierarce** [comment]
Oh, there's actually a limit value for the offset option: 

`When using the offset parameter the maximum limit on the offset is 1000. If you would like to get more results than that use either before or after.`

I guess you could modify the script to use `before` or `after`. I'll create a ticket for that. 

Thanks for reporting this (and sorry it took me so much time to answer you.)

**Comment by javierarce** [comment]
This should be fixed by the last merged PR.
